### PR TITLE
build_matrix.sh: Run "git show --oneline -s"

### PR DESCRIPTION
**Pull request by fxlb**

### CODE REVIEW

**Comment by infrastation** [comment]
`git describe` may do the job too (not tested).

**Comment by infrastation** [comment]
With this change the build matrix now can pause waiting for user input. Steps to reproduce:
1. Set git configuration `core.pager` to `less -S`.
2. Have the terminal width small enough or the `HEAD` commit summary long enough for the output of `git show --oneline -s` to be longer than the number of terminal columns.
3. Run `./build_matrix.sh` and see it waiting for `less` to exit.

**Comment by guyharris** [comment]
There is an award called the ["Useless Uses of Cat Award"](https://porkmail.org/era/unix/award) (as opposed to [useful uses of *a* cat](https://www.facebook.com/UNILADTech/videos/using-a-cat-to-feed-wires/1560196204547217/)).

That said:

```
$ git show --oneline -s
5d71e580 (HEAD -> master, origin/master, origin/HEAD) pcap_dump_close: don't close stdout, just flush it.
(END)
```

vs.

```
$ git show --oneline -s | cat
5d71e580 pcap_dump_close: don't close stdout, just flush it.
$ 
```

so, as a result of git "helpfully" running a pager, piping its output to cat may either convince git not to run a pager or convince the pager not to page anything, as the output is a pipe but not a terminal.

I tried this by narrowing my Terminal window and running both `git show --oneline -s | less -S` and `git show --oneline -s | less -S | cat` - the former stopped, the later didn't.

**Comment by guyharris** [comment]
(And I have ***NO*** idea whose brilliant idea it was to have the output of `git show --oneline -s` depend on whether it's writing to a terminal or not.)

**Comment by infrastation** [comment]
Making the pager conditional on `isatty()` (which the `cat` indeed deactivates) in general makes sense to me because this way git does not overwhelm the terminal with output that is supposed to be long (e.g. `git log`).  Arguably, `git show --oneline` looks like a corner case, but is not treated as one.

In this case `less` kicks in for one line of input because there's a part of this line outside of the visible area, just like when an input takes more than one page vertically. When the content fits both horizontally and vertically, it does not kick in because git sets the "quit if one screen" less option by default. This can be tested as follows using different terminal sizes:
```
date | LESS=FRX less -S
```

**Comment by infrastation** [comment]
Either of the following would also work:
```
git -c core.pager= show --oneline -s
git -c core.pager=cat show --oneline -s
```

**Comment by infrastation** [comment]
On my host both commands produce identical output (with the list of refs after commit ID), except the former uses colours and the latter does not. I do not have a strong preference so long as it works both in my working copy and in the CI.

**Pull request merged**
